stages:
  - Lint
  - Compile
  - Security_scan
  - Test
  - Quality
  - Package
  - Review
  - Staging
  - Production
  - Deployment_validation



flake8:
  image: docker:latest
  stage: Lint
  
  services:
    - docker:dind
  script:
    - apk add --no-cache python3 py3-pip
    - python3 -m venv /path/to/venv
    - . /path/to/venv/bin/activate
    - pip install --upgrade pip setuptools importlib_metadata
    - pip install flake8
    - flake8 --ignore=E501,E303 .

docker_linter:
  image: docker:latest
  stage: Lint
  services:
    - docker:dind
  script:
    - apk add --no-cache wget
    - wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
    - chmod +x /usr/local/bin/hadolint
    - hadolint Dockerfile

compile:
  image: docker:latest
  stage: Compile
  services:
    - docker:dind
  script:
    - docker build -t gitlabprojet .
  artifacts:
    paths:
      - docker_image.tar

test:
  stage: Test
  image: docker:latest
  services:
    - docker:dind
  script:
    # Exécuter le fichier test.py à l'intérieur de l'image
    - docker run --rm gitlaprojet python test.py